version: "3.9"

services:
  message-broker:
    image: rabbitmq:3-management-alpine
    container_name: img-processing-msg-broker
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ${HOME}/dev-rabbitmq/data/:/var/lib/rabbitmq
      - ${HOME}/dev-rabbitmq/log/:/var/log/rabbitmq
    restart: always
    networks:
      - dev-rabbit-network


networks:
  dev-rabbit-network:
    driver: bridge
